const categories = {
  randomall: {
    words: [
      "여기",
      "여긴",
      "케익",
      "노바",
      "쏟아지는",
      "해야",
      "평온했던",
      "첫만남",
      "BOOM",
      "저 거위도",
      "떠나는길에",
      "봄눈",
      "마라탕",
      "hey",
      "사탕",
      "내가 S면",
      "만세",
      "음악의신",
      "끼부리지마",
      "let go",
      "어머님",
      "은하수",
      "소원",
      "뽀삐뽀삐",
      "강남",
      "hallo",
      "Cause",
      "붉은색",
      "Maniac",
      "touch",
      "총 맞은것 처럼",
      "전에 알던",
      "너무 치사하잖아",
      "내 걱정말고",
      "거부 할 수 없는 너의 마력",
      "겉으론 Bad girl",
      "Every",
      "내가 제일",
      "Girl's",
      "Roly",
      "내꺼하자",
      "Good-bye Baby",
      "So Cool",
      "Cry Cry",
      "Mr. Simple",
      "낮에는",
      "와우",
      "MAMA",
      "니가 있는곳",
      "숨겨도",
      "Alone",
      "Day By Day",
      "나 으르",
      "I Got a Boy",
      "Everybody",
      "Give It To Me",

      "길을 잃었다",

      "다 같이 원",
      "Overdose",
      "Mr.Mr.",
      "Eyes, Nose, Lips",
      "말리지마",
      "Boy In Luv",
      "Happiness",
      "Touch My Body",

      "Call Me Baby",
      "I Need U",
      "주세요",
      "Like OOH-AHH",
      "널 향한",
      "Tell me ",

      "피 땀",
      "Cheer Up",
      "휘 - 파",

      "시간을",
      "Monster",

      "아주!",
      "DNA",
      "Knock Knock",

      "Energetic",
      "빨",

      "Fingertip",
      "Cherry Bomb",
      "Fake Love",
      "DDU-DU DDU-DU",
      "What is Love?",
      "Bad Boy",
      "La Vie en Rose",

      "Boy With Luv",
      "Kill This Love",
      "달라",
      "Fancy",

      "Dynamite",
      "How You Like That",
      "Wannabe",

      "Fiesta",

      "Butter",
      "Next Level",
      "Alcohol-Free",

      "1,2,3,4",
      "숨 참고",
      "Attention",
      "MANIAC",
      "HOT",
      "OMG",
      "Pink Venom",
      "길을",
    ],
    translations: {
      여기: "빅뱅 - 판타스틱 베이비",
      여긴: "윤하 - 사건의 지평선",
      케익: "티라미수 케익",
      노바: "에스파 - Supernova",
      쏟아지는: "QWER - 고민중독 / 트와이스 - Dance The Night Away",
      해야: "IVE - 해야",
      평온했던: "아이들 - 나는 아픈건 딱 질색이니까",
      첫만남: "TWS - 첫 만남은 계획대로 되지 않아",
      BOOM: "RIIZE - Boom Boom base / 르세라핌 - 이브 프시케 ...",
      "저 거위도": "악뮤 - 후라이의 꿈",
      떠나는길에: "비비 - 밤양갱",
      봄눈: "펜타곤 - 봄눈 / 10cm - 봄눈 ",
      마라탕: "서이브 - 마라탕후루",
      hey: "자우림 - hey hey / TWS - HEY HEY",
      사탕: "twice - what is love?",
      "내가 S면": "TWS - 내가 S면 넌 나의 N이 되어줘",
      만세: "세븐틴 - 만세",
      음악의신: "세븐틴 - 음악의 신",
      끼부리지마: "위너 - 끼부리지마",
      "let go": "윤하 - 오르트구름",
      어머님: "JYP - 어머님이 누구니",
      은하수: "볼빨간사춘기 - 우주를 줄게",
      소원: "소녀시대 - 소원을 말해봐",
      뽀삐뽀삐: "티아라 - 뽀삐뽀삐",
      강남: "싸이 - 강남스타일",
      hallo: "카라 - 루팡",
      Cause: "뉴진스 - Hype boy",
      붉은색: "이무진 - 신호등",
      Maniac: "스테이키즈 , 비비지 - Maniac",
      touch: "씨스타 - touch my body ",
      "총 맞은것 처럼": "백지영 - 총맞은것처럼 / 빅뱅 - 뱅뱅뱅",
      "전에 알던": "소녀시대 - Oh!",
      "너무 치사하잖아": "2NE1 - Go Away",
      "내 걱정말고": "2NE1 - Go Away",
      "거부 할 수 없는 너의 마력": "샤이니 - Lucifer",
      "겉으론 Bad girl": "Miss A - Bad Girl Good Girl",
      Every: "비스트 - Shock  ",
      "내가 제일": "2NE1 - 내가 제일 잘 나가, 레드벨벳 - 빨간맛",
      "Girl's": "소녀시대 - The Boys",
      Roly: "T-ara - 롤리폴리",
      내꺼하자: "인피니트 - 내꺼하자",
      "Good-bye Baby": "Miss A - 굿바이 베이비",
      "So Cool": "씨스타 - 쏘쿨",
      "Cry Cry": "티아라 - Cry Cry",
      "Mr. Simple": "슈퍼주니어 - Mr. Simple",
      낮에는: "싸이 - 강남스타일",
      와우: "빅뱅 - 판타스틱 베이비",
      MAMA: "EXO - MAMA",
      "니가 있는곳": "에일리 - Heaven",
      숨겨도: "태티서 - Twinkle",
      Alone: "씨스타 - 나혼자",
      "Day By Day": "티아라 - Day By Day",

      "나 으르": "EXO - 으르렁",
      "I Got a Boy": "소녀시대 - I Got a Boy",
      Everybody: "샤이니 - Everybody",
      "Give It To Me": "씨스타 - Give It To Me",

      "길을 잃었다": "아이유 - 분홍신",

      "다 같이 원": "크레용팝 - 빠빠빠",
      Overdose: "EXO - 중독",
      "Mr.Mr.": "소녀시대 - Mr.Mr.",
      "Eyes, Nose, Lips": "태양 - 눈, 코, 입",
      말리지마: "AOA - 짧은 치마",
      "Boy In Luv": "방탄소년단 - 상남자",
      Happiness: "레드벨벳 - 행복",
      "Touch My Body": "씨스타 - Touch My Body",
      "Bang Bang": "빅뱅 - 뱅뱅뱅, Jessie J - Bang Bang",
      "Call Me Baby": "EXO - Call Me Baby",
      "I Need U": "방탄소년단 - I Need U",
      주세요: "레드벨벳 - Ice Cream Cake",
      "Like OOH-AHH": "트와이스 - OOH-AHH하게",
      "널 향한": "여자친구 - 오늘부터 우리는",
      "Tell me ": "소녀시대 - Lion Heart , 원더걸스 - Tell me",
      "피 땀": "방탄소년단 - 피 땀 눈물",
      "Cheer Up": "트와이스 - Cheer Up",
      "휘 - 파": "블랙핑크 - 휘파람",
      시간을: "여자친구 - 시간을 달려서",
      Monster: "EXO - Monster",

      "아주!": "세븐틴 - 아주 NICE",
      DNA: "방탄소년단 - DNA",
      "Knock Knock": "트와이스 - Knock Knock",

      Energetic: "워너원 - 에너제틱",
      빨: "레드벨벳 - 빨간 맛",

      Fingertip: "여자친구 - Fingertip",
      "Cherry Bomb": "NCT 127 - Cherry Bomb",
      "Fake Love": "방탄소년단 - Fake Love",
      "DDU-DU DDU-DU": "블랙핑크 - 뚜두뚜두",
      "What is Love?": "트와이스 - What is Love?",
      "Bad Boy": "레드벨벳 - Bad Boy",
      "La Vie en Rose": "아이즈원 - 라비앙로즈",

      "Boy With Luv": "방탄소년단 - 작은 것들을 위한 시 (feat. Halsey)",
      "Kill This Love": "블랙핑크 - Kill This Love",
      달라: "ITZY - 달라달라",
      Fancy: "트와이스 - Fancy",

      Dynamite: "방탄소년단 - Dynamite",
      "How You Like That": "블랙핑크 - How You Like That",
      Wannabe: "ITZY - Wannabe",

      Fiesta: "아이즈원 - Fiesta",

      Butter: "방탄소년단 - Butter",
      "Next Level": "에스파 - Next Level",
      "Alcohol-Free": "트와이스 - Alcohol-Free",

      "1,2,3,4": "아이브 - eleven, ",

      "숨 참고": "아이브 - Love Dive",

      Attention: "뉴진스 - Attention",

      MANIAC: "스트레이 키즈 - MANIAC , 비비지 - MANIAC",
      HOT: "세븐틴 - HOT , 원더걸스 - So Hot",
      OMG: "뉴진스 - OMG",
      "Pink Venom": "블랙핑크 - Pink Venom",

      길을: "아이유 - 분홍신",
    },
  },
};
